let LETTERS=[];
async function loadLetterTypes(){const r=await api("jenisSurat");LETTERS=r.items||[]}
function renderChat(){const v=document.getElementById("chatView");v.innerHTML=`<div class="page-title"><div><h2>Layanan Surat</h2><span class="muted">Ajukan surat lewat alur chat.</span></div></div><div class="chat-shell"><div class="chat-head"><div><b>🤖 FIKOM Assistant</b><small>Layanan Surat Digital</small></div><span class="badge">Online</span></div><div id="chatBody" class="chat-body"></div><div class="chat-input"><input id="chatText" placeholder="Tulis pesan..."><button id="chatSend" class="primary-btn">Kirim</button></div></div>`;
const b=document.getElementById("chatBody");bot("Halo 👋 Saya siap membantu pengajuan surat Anda.");bot("Pilih jenis surat yang ingin diajukan:");const a=document.createElement("div");a.className="chat-actions";LETTERS.forEach(x=>{const q=document.createElement("button");q.className="quick";q.textContent=`📄 ${x.nama_surat}`;q.onclick=()=>showLetterForm(x);a.appendChild(q)});b.appendChild(a);document.getElementById("chatSend").onclick=sendChat}
function bot(t){addBubble(t,"bot")}function me(t){addBubble(t,"me")}function addBubble(t,c){const b=document.getElementById("chatBody"),x=document.createElement("div");x.className=`bubble ${c}`;x.innerHTML=esc(t);b.appendChild(x);b.scrollTop=b.scrollHeight}
function sendChat(){const i=document.getElementById("chatText");if(!i.value.trim())return;me(i.value.trim());i.value="";setTimeout(()=>bot("Untuk pengajuan baru, pilih jenis surat dari tombol layanan."),200)}
function showLetterForm(type){const b=document.getElementById("chatBody");b.innerHTML=`<div class="bubble bot">Siap. Kita buat <b>${esc(type.nama_surat)}</b>.</div><div class="panel"><div class="stepper"><span class="step current">1 Data</span><span class="step">2 Lampiran</span><span class="step">3 Konfirmasi</span></div><div class="form-grid"><div><label>Keperluan</label><input id="fKeperluan" required></div><div><label>Tujuan Surat</label><input id="fTujuan" required></div><div class="full-col"><label>Catatan</label><textarea id="fCatatan" rows="3"></textarea></div><div class="full-col upload-box"><b>📎 Lampiran</b><br><small>Maksimum mengikuti kebijakan server.</small><input id="fFile" type="file" multiple accept=".pdf,.jpg,.jpeg,.png"></div></div><button id="submitLetter" class="primary-btn full" style="margin-top:15px">Kirim Pengajuan →</button></div>`;document.getElementById("submitLetter").onclick=()=>submitApplication(type)}
async function submitApplication(type){try{const files=await readFiles(document.getElementById("fFile").files);const r=await api("createPengajuan",{jenisKode:type.kode,keperluan:document.getElementById("fKeperluan").value.trim(),tujuan:document.getElementById("fTujuan").value.trim(),catatan:document.getElementById("fCatatan").value.trim(),files});toast("Pengajuan berhasil: "+r.ticket_no);renderPengajuan()}catch(e){toast(e.message,true)}}
function readFiles(fs){return Promise.all([...fs].map(f=>new Promise((ok,no)=>{if(f.size>10*1024*1024){no(Error("Ukuran file maksimal 10 MB per file."));return}const r=new FileReader();r.onload=()=>ok({name:f.name,mimeType:f.type,size:f.size,data:r.result.split(",")[1]});r.onerror=()=>no(Error("Gagal membaca file."));r.readAsDataURL(f)})))}
